### PR TITLE
Knit README

### PR DESCRIPTION
**Pull request by philip-khor**
https://github.com/NickCH-K/pmdplyr/issues/35#issuecomment-522803819

### CODE REVIEW

**Comment by NickCH-K** [comment]
The part it seemed not to like was code_of_conduct - does this address that problem?

**Comment by philip-khor** [comment]
Yeah it does. The issue was that CRAN detected an invalid link .github/CODE_OF_CONDUCT.md. Since we don't include it in the build (.RBuildignore) CRAN returns an error. I just replaced it with a link to the pkgdown site, which shouldn't be an issue.

**Comment by NickCH-K** [comment]
Cool! Good to go then.

**Comment by philip-khor** [comment]
Alright - I don't remember if I did submit_cran though, and it's not showing up in the incoming FTP. Just ran submit_cran again so you may get a duplicate email that's safe to ignore.

**Pull request merged**
