### PR TITLE
pkgdown site for pmdplyr

### PR DESCRIPTION
**Pull request by philip-khor**
This PR creates a simple pkgdown site in the docs directory that can be deployed using [GitHub Pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch). 

Preview of this pkgdown site is available at https://pedantic-poitras-55e93b.netlify.com/. 

Note: this also adds the internal keyword to `build_pdeclare()` as it should not be user-facing.

### CODE REVIEW

**Comment by NickCH-K** [comment]
You're doing so much good work on this

**Comment by NickCH-K** [comment]
`gh-pages` branch is created and live: https://nickch-k.github.io/pmdplyr/

**Comment by philip-khor** [comment]
Shouldn't require a separate branch. I think master branch /docs should do ...

**Comment by NickCH-K** [comment]
Oh! Well that's convenient. I'll delete the additional branch.

**Comment by NickCH-K** [comment]
Alright, NOW it is live https://nickch-k.github.io/pmdplyr/

**Pull request merged**
